name: Publish

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci --ignore-scripts
      - run: npm test
      - name: Set output
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ steps.version.outputs.tag }}
          dry-run: true
